[workspace]
members = [
  "crates/codebook",
  "crates/codebook-config",
  "crates/codebook-lsp",
  "crates/downloader",
]
resolver = "2"

[workspace.package]
version = "0.2.13"
authors = ["Codebook Contributors"]
description = "A code-aware spell checker for developers"
repository = "https://github.com/blopker/codebook"
homepage = "https://github.com/blopker/codebook"
documentation = "https://github.com/blopker/codebook"
license = "MIT"
edition = "2024"

# Note, all dependencies MUST be available on crates.io, no git imports, or Codebook cannot be released as a crate.
[workspace.dependencies]

anyhow = "1.0.71"
base16ct = { version = "<2", features = ["alloc"] }
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5.26", features = ["derive"] }
dirs = "6.0.0"
env_logger = "0.11.6"
glob = "0.3"
globset = "0.4"
ignore = "0.4"
log = "0.4.22"
lru = "0.18"
regex = "1.11.1"
reqwest = { version = "^0.13.0", default-features = false, features = [
  "blocking",
  "rustls",
  "json",
] }
rustls = { version = "<0.24", features = ["aws-lc-rs"] }
rustls-platform-verifier = "0.7.0"
webpki-roots = "<2"
serde = { version = "1", features = ["derive", "serde_derive"] }
serde_json = "1"
sha2 = "<0.12"
spellbook = "<0.5.0"
streaming-iterator = "0.1.9"
string-offsets = "0.2.0"
tempfile = "3"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
toml = "<2"
tower-lsp = "0.20.0"
tree-sitter = "<0.27.0"
tree-sitter-bash = "<0.26.0"
tree-sitter-c = "<0.25.0"
tree-sitter-c-sharp = "<0.24.0"
tree-sitter-cpp = "<0.25.0"
tree-sitter-css = "<0.26.0"
tree-sitter-dart = "<1"
tree-sitter-elixir = "<0.4.0"
tree-sitter-erlang = "<0.21.0"
tree-sitter-go = "<0.26.0"
tree-sitter-haskell = "<0.25.0"
tree-sitter-html = "<0.25.0"
tree-sitter-java = "<0.25.0"
tree-sitter-javascript = "<0.26.0"
tree-sitter-lua = "<0.25.0"
tree-sitter-md = "<0.6.0"
tree-sitter-nix = "0.3.0"
tree-sitter-ocaml = "<0.26"
tree-sitter-odin-codebook = "1.4.0"
tree-sitter-php = "<0.25.0"
tree-sitter-python = "<0.26.0"
tree-sitter-r = "1.1.0"
tree-sitter-ruby = "0.23.1"
tree-sitter-rust = "<0.25.0"
tree-sitter-swift = "<0.8.0"
tree-sitter-toml-ng = "<0.8.0"
tree-sitter-typescript = "0.23.2"
tree-sitter-vhdl = "<2"
tree-sitter-yaml = "0.7.2"
tree-sitter-zig = "<2"
codebook-tree-sitter-just = "<0.2.0"
codebook-tree-sitter-latex = "<0.7.0"
codebook-tree-sitter-typst = "<0.13.0"
unicase = "2.9"
unicode-script = "0.5.8"
unicode-segmentation = "1.12.0"

pprof = { version = "0.15", features = ["flamegraph"] }

codebook = { path = "crates/codebook", version = "0.3.0" }
codebook_config = { path = "crates/codebook-config", version = "0.3.0" }
codebook_downloader = { path = "crates/downloader", version = "0.3.0" }


[profile.release]
lto = "thin"
# debug=true

[profile.fast-release]
inherits = "release"
debug-assertions = true
opt-level = 0
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
